[package]
name = "Fulgurant"
version = "0.1.0"
edition = "2021"
license = "Apache-2.0"
readme = "README.md"
keywords = ["rust", "web", "api", "server", "fulgur", "sync"]
categories = ["web", "api", "server"]
homepage = "https://fulgur.app"

[dependencies]
# Web framework
axum = { version = "0.8.8", features = ["macros"] }
tokio = { version = "1.48.0", features = ["full"] }
tower = "0.5.2"
tower-http = { version = "0.6.8", features = ["fs", "trace"] }

# Types
fulgur-common = { path = "../Fulgur-common" }

# Database
sqlx = { version = "0.8.6", features = ["runtime-tokio-rustls", "sqlite", "migrate", "chrono"] }

# Templating
askama = "0.15.0"
askama_axum = "0.4"

# Serialization
serde = { version = "1.0.228", features = ["derive"] }
serde_json = "1.0.146"

# Error handling
thiserror = "2.0.17"
anyhow = "1.0.100"

# Logging
tracing = "0.1.44"
tracing-subscriber = { version = "0.3.22", features = ["env-filter"] }
tracing-appender = "0.2"

# Utilities
uuid = { version = "1.19.0", features = ["v4", "serde"] }
dotenvy = "0.15.7"
chrono = { version = "0.4.42", features = ["serde"] }
rand = "0.9.2"
rand_core = "0.9.3"
base64 = "0.22.1"
argon2 = "0.5.3"
totp-rs = { version = "5.7.0", features = ["qr", "otpauth", "gen_secret"] }
tower-sessions = "0.14.0"
lettre = "0.11.19"
regex = "1.12.2"
sha2 = "0.10.9"

[dev-dependencies]
http-body-util = "0.1.3"
